# Only workflow in this repo. Triggers sync from dev into ekbatashoonya.github.io (runs that repo's sync-lovable.yml from its default branch, main).
# Add secret REPO_DISPATCH_TOKEN in this repo (Settings → Secrets) with access to trigger workflows in ekbatashoonya/ekbatashoonya.github.io.

name: Trigger sync to GitHub Pages repo

on:
  push:
    branches:
      - dev   # only when dev changes
  workflow_dispatch:   # or run manually from Actions

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync workflow in pages repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ekbatashoonya/ekbatashoonya.github.io/dispatches \
            -d '{"event_type":"sync-from-lovable"}'
